
name: Package Application with Pyinstaller

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Package Application - Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v4
      with:
        name: MFM-win64
        path: src/dist/windows

    - name: Package Application - Linux
      uses: JackMcKew/pyinstaller-action-linux@python3.10
      with:
        path: src

    - uses: actions/upload-artifact@v4
      with:
        name: MFM-linux32
        path: src/dist/linux
